// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykvgutrrxtqinpbfbovw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlrdmd1dHJyeHRxaW5wYmZib3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODUxNjAsImV4cCI6MjA2NTU2MTE2MH0.jURTEkAHZwb6rqqdmjzfZmQcccwCnzaMcOVwALrXhZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);